default: &default
  adapter: postgresql
  pool: 5
  username: postgres
  password: root

development:
  <<: *default
  database: school_development

test:
  <<: *default
  database: school_test

production:
  <<: *default
  database: school_production
